"""
Assets to test fanning out sections to files that are linked from the sections.
"""

# sections
SECTION_AT_NOON = """## 2020-01-01 12:00 - Some title at noon
Some text [[Non-existing link]]"""

SECTION_AT_MIDNIGHT = """## 2020-01-01 00:00 - Some title at midnight
Some text [[Existing link]] and dublicate [[Existing link]]
[[Non-existing link]]"""

SECTION_AT_SIX_AM_ALREADY_IN_EXISTING_LINK = """## 2020-01-01 06:00
Some text [[Existing link]]"""

SECTION_AT_ELEVEN_WITH_DOT = """## 2020-01-01 11:00 - Some title at eleven
Some text [[Non-existing link.com]]"""

EMPTY_SECTION = """## 2020-01-01 00:00 - Some title at midnight"""


# input
CONTENT_TO_FAN_OUT = f"""# Main title
Text

{SECTION_AT_SIX_AM_ALREADY_IN_EXISTING_LINK}


{SECTION_AT_NOON}


{SECTION_AT_MIDNIGHT}

{EMPTY_SECTION}"""


CONTENT_TO_FAN_OUT_WITH_DOT = CONTENT_TO_FAN_OUT + "\n\n" + SECTION_AT_ELEVEN_WITH_DOT


# existing link
EXISTING_LINK_CONTENT_BEFORE = f"""# Existing link
Text


{SECTION_AT_SIX_AM_ALREADY_IN_EXISTING_LINK}"""


EXISTING_LINK_CONTENT_AFTER = f"""# Existing link
Text


{SECTION_AT_MIDNIGHT}


{SECTION_AT_SIX_AM_ALREADY_IN_EXISTING_LINK}"""


# link to create (non-existing)
NON_EXISTING_LINK_CONTENT_AFTER = f"""{SECTION_AT_MIDNIGHT}


{SECTION_AT_NOON}"""


# files
FILE_NAME_TO_FAN = "2020-01-01.md"
EXISTING_FILE_NAME = "Existing link.md"
NON_EXISTING_FILE_NAME = "Non-existing link.md"
NON_EXISTING_FILE_NAME_WITH_DOT = "Non-existing link.com.md"


FILES_IN = {
    FILE_NAME_TO_FAN: CONTENT_TO_FAN_OUT,
    EXISTING_FILE_NAME: EXISTING_LINK_CONTENT_BEFORE,
}


FILES_OUT = {
    FILE_NAME_TO_FAN: CONTENT_TO_FAN_OUT,
    EXISTING_FILE_NAME: EXISTING_LINK_CONTENT_AFTER,
    NON_EXISTING_FILE_NAME: NON_EXISTING_LINK_CONTENT_AFTER,
}

FILES_IN_WITH_DOT = {
    FILE_NAME_TO_FAN: CONTENT_TO_FAN_OUT_WITH_DOT,
    EXISTING_FILE_NAME: EXISTING_LINK_CONTENT_BEFORE,
}

FILES_OUT_WITH_DOT = {
    FILE_NAME_TO_FAN: CONTENT_TO_FAN_OUT_WITH_DOT,
    EXISTING_FILE_NAME: EXISTING_LINK_CONTENT_AFTER,
    NON_EXISTING_FILE_NAME: NON_EXISTING_LINK_CONTENT_AFTER,
    NON_EXISTING_FILE_NAME_WITH_DOT: SECTION_AT_ELEVEN_WITH_DOT,
}
